### ISSUE TITLE
Load Transition Altitude from DB

### ISSUE THREAD

**Issue by St54Kevin** [flybywiresim/aircraft#2068]
**Mod Version**

master of 23rd of Nov 20

**Describe the bug**

Transition ALT on the takeoff or Approach page is defaulted to 10000ft. It should be taken from the nav database and inserted automatically depending on the DEP/ARR airport.

**References**

IRL experience

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
We need to see if we can find this using the info provided by `FacilityLoader`.

Otherwise, correct me if I'm wrong, but couldn't we use our online ATIS for this if we can't find it using `FacilityLoader` ?

**Comment by St54Kevin** [comment]
> We need to see if we can find this using the info provided by `FacilityLoader`.
> 
> Otherwise, correct me if I'm wrong, but couldn't we use our online ATIS for this if we can't find it using `FacilityLoader` ?

Do you have actual ATIS for every airport out there? Also when airports are closed, there is no ATIS

**Comment by Benjozork** [comment]
Well it's nowhere near a perfect solution, but if we can't get the transition alt from nav data, it would be better than nothing, no ?

**Comment by St54Kevin** [comment]
Of course. But is it reliable?

**Comment by CBGonzalez** [comment]
As far as I can see, the current nav data in MSFS does not contain the transition altitude for airports (there´s no documented field for it at least).

**Comment by beheh** [comment]
The ToLiss has a setting for this in it's ISCS. For now we could make it user-configurable in the MCDU until we have a better source (as I believe it's usually the same per-country or at least per-region).

**Comment by St54Kevin** [comment]
> As far as I can see, the current nav data in MSFS does not contain the transition altitude for airports (there´s no documented field for it at least).

What about navigraph?

**Comment by Kimbyeoungjang** [comment]
i setup the default trans alt to 10,000ft because that was MCDU default value.
currently, there is no automatically trans alt input. you manually insert that value.

**Comment by danieldjewell** [comment]
As @St54Kevin mentioned, I don't think ATIS is a reliable source for TA/TL. (Which also raises another point to be mindful of -- Transition *Altitude* and Transition *Level* are two different numbers. *Often* they are the same, but not always. [This article on Code 7700](http://www.code7700.com/ta_tl.htm) offers a nice explanation of the differences - with references to the ICAO source documents.)

That said, I *believe* that TL/TA is on a per-country basis - that is, it doesn't change airport-to-airport within a single country? (Similar to how a country standardizes on giving QNH (or QFE for that matter) in hPa or inHg.) 

Would a temporary work-around be a simple array to lookup the default? (e.g. in the US, 18,000/FL180, etc.?)

**Comment by CBGonzalez** [comment]
> 
> 
> > As far as I can see, the current nav data in MSFS does not contain the transition altitude for airports (there´s no documented field for it at least).
> 
> What about navigraph?

Wouldn´t know, dont´have it anymore...

**Comment by CBGonzalez** [comment]
Maybe, for the time being, the field could display as [ ], as specified in the Honeywell manual (Preflight 4-82) when the transition altitude is not in the database?

**Comment by saintwolf** [comment]
All Navigraph charts I have seen show the Transition Level as "By ATC"

**Comment by crisk73** [comment]
Transition Level is always "by ATC" as depends on local QNH. Transition ALT is fixed for each ICAO.

**Comment by BlueberryKing** [comment]
It seems to me this has been implemented in https://github.com/flybywiresim/a32nx/pull/6200. Is there something that is requested here which is still missing? CC: @tracernz

**Comment by tracernz** [comment]
We don’t load it from the DB, only from simbrief OFPs if you happen to use simbrief. cfms-20 will have a proper solution. 😉
